### ISSUE TITLE
Unable to access the recon-ninja after successful setup

### ISSUE THREAD

**Issue by thedr34mb0y** [tess-ss/recon-ninja#2]
I have completed my setup with the mentioned flow however it does not give me any connection to my 3000 port here is how my setup files look like

Content of `src/axiosConfig.js`

```
root@reconmaster:/opt/recon-ninja/Backend# cat ../Frontend/src/axiosConfig.js
import axios from "axios"
const data=localStorage.getItem("userLoginInfo")?JSON.parse(localStorage.getItem("userLoginInfo")):null
axios.defaults.baseURL = 'http://104.237.xx.xx:3000/';
export const changeHeaders=(token)=>{
    axios.defaults.headers.common['Authorization'] ="Bearer "+token;
}
if (data){
    axios.defaults.headers.common['Authorization'] ="Bearer "+data.token;
```

Content of `db.js` 

```
root@reconmaster:/opt/recon-ninja/Backend# cat db.js 
const mongoose=require('mongoose')
const connectDB=async()=>{
    try{
        await mongoose.connect('mongodb+srv://reconmaster.xxxxx.mongodb.net/')
        console.log('Connected!');
    }
    catch (err){
        console.log("Unexpected Error",err);
    }
}

module.exports=connectDB
```
Then I started my server as shown in the screenshot below:

![image](https://user-images.githubusercontent.com/66123314/223617323-22531f1f-8054-4e22-bc28-e118fedf7404.png)

However, It does not populate any data to my MongoDB server also it does not give any connection to port 3000 while accessing with my VPS public IP.

![image](https://user-images.githubusercontent.com/66123314/223617549-201388ca-71a8-440d-b98f-4e24b48daae9.png)

Let me know if any additional setup is required or if is there something that I missed. 

Thanks!

**Comment by tess-ss** [comment]
Hello @thedr34mb0y ,

Thank you for raising this issue, can you confirm what environment are you trying to install this and confirm the status of redis-server?

Thanks,
tess

**Comment by thedr34mb0y** [comment]
Hi @tess-ss ,

Thanks for your swift response, here are the details of my environment and the redis-server status proof.

![image](https://user-images.githubusercontent.com/66123314/223619117-8e9543e5-2a02-4268-8793-0c5133c78816.png)

Also I am using the nodejs version `v12.22.9`

**Comment by tess-ss** [comment]
Please update the node version to latest, which should fix the issue.

Thanks,
tess

**Comment by thedr34mb0y** [comment]
Hello @tess-ss ,

Thanks, buddy for your swift response I updated the node version as per your advice it works fine for me with node version `v18.14.2`

![image](https://user-images.githubusercontent.com/66123314/223622730-3104bdac-9250-48bb-a7ae-f1361058ca5c.png)


Really appreciate you looking into it

Cheers,
Sid!

**Comment by tess-ss** [comment]
Sweet @thedr34mb0y 👍🏻 

Thanks,
tess
